# Generated by Django 5.1.1 on 2024-10-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Car Name')),
                ('brand', models.CharField(max_length=100, verbose_name='Car Brand')),
                ('model', models.CharField(max_length=100, verbose_name='Car Model')),
                ('price', models.IntegerField(max_length=100, verbose_name='Car Price')),
            ],
        ),
    ]
